//! Server handler registry generation module.
//!
//! This module generates a handler registry system that maps operation paths
//! to handler implementations at runtime, allowing dynamic handler registration
//! and lookup with fallback to default not-implemented handlers.

use crate::generator::{GeneratorConfig, GeneratorError};
use crate::parser::YangModule;

/// Generator for server handler registry.
#[allow(dead_code)]
pub struct RegistryGenerator<'a> {
    config: &'a GeneratorConfig,
}

#[allow(dead_code)]
impl<'a> RegistryGenerator<'a> {
    /// Create a new registry generator with the given configuration.
    pub fn new(config: &'a GeneratorConfig) -> Self {
        Self { config }
    }

    /// Generate the handler registry implementation for a YANG module.
    ///
    /// This creates a HandlerRegistry type that can store and lookup
    /// handler implementations by path pattern, with support for
    /// default not-implemented handlers.
    pub fn generate_registry(&self, module: &YangModule) -> Result<String, GeneratorError> {
        let mut output = String::new();

        // Generate file header
        output.push_str("// This file is automatically generated by rustconf.\n");
        output.push_str("// DO NOT EDIT MANUALLY.\n\n");
        output.push_str(
            "#![allow(unused_imports, unused_variables, dead_code, clippy::module_inception)]\n\n",
        );

        // Add use statements
        output.push_str("use async_trait::async_trait;\n");
        output.push_str("use rustconf_runtime::{ServerRequest, ServerResponse, ServerError};\n");
        output.push_str("use std::collections::HashMap;\n");
        output.push_str("use std::sync::Arc;\n");
        output.push_str("use super::handlers::*;\n");
        output.push('\n');

        // Generate handler function type
        let trait_name = self.generate_trait_name(module);
        output.push_str("/// Type alias for handler functions.\n");
        output.push_str("///\n");
        output.push_str(
            "/// Handler functions take a request and return a response asynchronously.\n",
        );
        output.push_str("pub type HandlerFn<H> = Arc<dyn Fn(Arc<H>, ServerRequest) -> std::pin::Pin<Box<dyn std::future::Future<Output = ServerResponse> + Send>> + Send + Sync>;\n");
        output.push('\n');

        // Generate HandlerRegistry struct
        output.push_str("/// Registry for mapping operation paths to handler implementations.\n");
        output.push_str("///\n");
        output.push_str("/// The registry stores path patterns mapped to handler functions,\n");
        output.push_str("/// allowing dynamic registration and lookup of handlers at runtime.\n");
        output
            .push_str("/// When no handler is registered for a path, a default not-implemented\n");
        output.push_str("/// handler is returned.\n");
        output.push_str(&format!(
            "pub struct HandlerRegistry<H: {}> {{\n",
            trait_name
        ));
        output.push_str("    /// Map of path patterns to handler functions\n");
        output.push_str("    handlers: HashMap<String, HandlerFn<H>>,\n");
        output.push_str("    /// The default handler implementation\n");
        output.push_str("    default_handler: Arc<H>,\n");
        output.push_str("}\n\n");

        // Generate HandlerRegistry implementation
        output.push_str(&format!(
            "impl<H: {} + 'static> HandlerRegistry<H> {{\n",
            trait_name
        ));

        // Constructor
        output.push_str("    /// Create a new handler registry with a default handler.\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Arguments\n");
        output.push_str("    ///\n");
        output.push_str("    /// * `default_handler` - The default handler to use when no specific handler is registered\n");
        output.push_str("    pub fn new(default_handler: H) -> Self {\n");
        output.push_str("        Self {\n");
        output.push_str("            handlers: HashMap::new(),\n");
        output.push_str("            default_handler: Arc::new(default_handler),\n");
        output.push_str("        }\n");
        output.push_str("    }\n\n");

        // Register method
        output.push_str("    /// Register a handler for a specific path pattern.\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Arguments\n");
        output.push_str("    ///\n");
        output.push_str(
            "    /// * `path` - The path pattern to register (e.g., \"/data/interfaces\")\n",
        );
        output.push_str("    /// * `handler` - The handler function to invoke for this path\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Returns\n");
        output.push_str("    ///\n");
        output.push_str("    /// Returns `Ok(())` if registration succeeds, or an error if the path is invalid.\n");
        output.push_str("    pub fn register(\n");
        output.push_str("        &mut self,\n");
        output.push_str("        path: impl Into<String>,\n");
        output.push_str("        handler: HandlerFn<H>,\n");
        output.push_str("    ) -> Result<(), ServerError> {\n");
        output.push_str("        let path = path.into();\n");
        output.push_str("        \n");
        output.push_str("        // Validate path format\n");
        output.push_str("        if path.is_empty() {\n");
        output.push_str("            return Err(ServerError::ValidationError(\n");
        output.push_str("                \"Handler path cannot be empty\".to_string()\n");
        output.push_str("            ));\n");
        output.push_str("        }\n");
        output.push_str("        \n");
        output.push_str("        // Store handler\n");
        output.push_str("        self.handlers.insert(path, handler);\n");
        output.push_str("        Ok(())\n");
        output.push_str("    }\n\n");

        // Lookup method
        output.push_str("    /// Look up a handler for a given path.\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Arguments\n");
        output.push_str("    ///\n");
        output.push_str("    /// * `path` - The path to look up (e.g., \"/data/interfaces\")\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Returns\n");
        output.push_str("    ///\n");
        output.push_str("    /// Returns the registered handler function if found, or a default\n");
        output.push_str(
            "    /// not-implemented handler if no handler is registered for this path.\n",
        );
        output.push_str("    pub fn lookup(&self, path: &str) -> HandlerFn<H> {\n");
        output.push_str("        // Try exact match first\n");
        output.push_str("        if let Some(handler) = self.handlers.get(path) {\n");
        output.push_str("            return handler.clone();\n");
        output.push_str("        }\n");
        output.push_str("        \n");
        output.push_str("        // Return default not-implemented handler\n");
        output.push_str("        Arc::new(move |_handler: Arc<H>, _request: ServerRequest| {\n");
        output.push_str("            Box::pin(async move {\n");
        output.push_str("                ServerResponse::from_error(\n");
        output.push_str("                    ServerError::NotFound(\n");
        output.push_str(
            "                        \"Handler not implemented for this path\".to_string()\n",
        );
        output.push_str("                    )\n");
        output.push_str("                )\n");
        output.push_str("            })\n");
        output.push_str("        })\n");
        output.push_str("    }\n\n");

        // Get default handler method
        output.push_str("    /// Get the default handler implementation.\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Returns\n");
        output.push_str("    ///\n");
        output.push_str("    /// Returns a reference to the default handler.\n");
        output.push_str("    pub fn default_handler(&self) -> &Arc<H> {\n");
        output.push_str("        &self.default_handler\n");
        output.push_str("    }\n\n");

        // List registered paths method
        output.push_str("    /// List all registered handler paths.\n");
        output.push_str("    ///\n");
        output.push_str("    /// # Returns\n");
        output.push_str("    ///\n");
        output.push_str("    /// Returns a vector of all registered path patterns.\n");
        output.push_str("    pub fn registered_paths(&self) -> Vec<String> {\n");
        output.push_str("        self.handlers.keys().cloned().collect()\n");
        output.push_str("    }\n");

        output.push_str("}\n");

        Ok(output)
    }

    /// Generate the trait name from the module name.
    fn generate_trait_name(&self, module: &YangModule) -> String {
        let module_type_name = crate::generator::naming::to_type_name(&module.name);
        format!("{}Handler", module_type_name)
    }
}
